apiVersion: v2
appVersion: 1.0.0
description: Outline helm deployment from https://github.com/SwanseaUniversityMedical/outline based on https://github.com/outline/outline.
name: outline
type: application
version: 0.0.0
