outline:
  resources:
    requests:
      memory: "1Gi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"

  storage:
    filesystem:
      enabled: false
    s3:
      enabled: true
      bucket: outline-demo
      bucketUrl: http://outline-demo.outline-minio:9000

  envFrom:
    - secretRef:
        name: outline-secret

  env:
    - name: LOG_LEVEL
      value: "silly"
    - name: DEBUG
      value: "http"

  persistence:
    enabled: false
    storageClassName: standard
    capacity: 1Gi

ingress:
  enabled: false

networkPolicy:
  enabled: false

keycloakWebhook:
  enabled: true

  # Override the outline container image
  image:
    repository: "test"
    tag: "1.0.0"

  envFrom:
    - secretRef:
        name: outline-secret-webhooks